In [4]:
import pandas as pd
print("1- covid dataframe")
df = pd.read_csv("covid_vaccine_statewise.csv")

covid dataframe

In [5]:
print("2-shape")
df.shape

2-shape

(7845, 24)

In [6]:
print('3. Display 20 % data')
df.sample(frac=.2)

3. Display 20 % data

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
1203,08/06/2021,Bihar,11231592.0,720074.0,2433.0,9362801.0,1868791.0,5162706.0,4198274.0,1821.0,...,NaN,NaN,NaN,2786932.0,3198367.0,3374528.0,NaN,NaN,NaN,9362801.0
5957,05/02/2021,Punjab,60878.0,3030.0,432.0,60878.0,0.0,31099.0,29775.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60878.0
6974,24/07/2021,Telangana,14010811.0,507515.0,1349.0,11070089.0,2940722.0,7283956.0,6724219.0,2636.0,...,6346306.0,4786331.0,2878174.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093,18/02/2021,Bihar,529891.0,12058.0,1328.0,497328.0,32563.0,198999.0,298029.0,300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,497328.0
2928,06/07/2021,Himachal Pradesh,4115822.0,132907.0,626.0,3398020.0,717802.0,2037875.0,2077124.0,823.0,...,1537963.0,1389410.0,1188449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3023,11/03/2021,Jammu and Kashmir,337836.0,51400.0,408.0,300120.0,37716.0,257298.0,80448.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,337836.0
2018,06/05/2021,Delhi,3693814.0,126950.0,922.0,2883317.0,810497.0,1676526.0,1206289.0,502.0,...,NaN,NaN,NaN,604542.0,1359039.0,919621.0,NaN,NaN,NaN,2883317.0
3202,06/02/2021,Jharkhand,86786.0,2827.0,380.0,86786.0,0.0,27825.0,58961.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86786.0
5425,20/05/2021,Nagaland,246683.0,25520.0,149.0,194835.0,51848.0,114594.0,80228.0,13.0,...,NaN,NaN,NaN,58534.0,86520.0,49760.0,NaN,NaN,NaN,194835.0
7606,20/07/2021,Uttarakhand,5373777.0,189913.0,672.0,4132892.0,1240885.0,2773007.0,2599168.0,1602.0,...,2221091.0,1721939.0,1430747.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
print('4. Display records for Karnataka State')
df.loc[df.State == "Karnataka"]

4. Display records for Karnataka State

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
3393,16/01/2021,Karnataka,3810.0,256.0,235.0,3810.0,0.0,1835.0,1975.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3810.0
3394,17/01/2021,Karnataka,4506.0,1385.0,1139.0,4506.0,0.0,2373.0,2133.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4506.0
3395,18/01/2021,Karnataka,14755.0,1999.0,1502.0,14755.0,0.0,6122.0,8633.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14755.0
3396,19/01/2021,Karnataka,25142.0,2788.0,1993.0,25142.0,0.0,10492.0,14649.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25142.0
3397,20/01/2021,Karnataka,36705.0,3687.0,2517.0,36705.0,0.0,13421.0,23283.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36705.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3600,11/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3601,12/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3602,13/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3603,14/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3604,15/08/2021,Karnataka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print('5. Display total Covaxin doses administered for karnataka')
df.loc[df.State=="Karnataka"," Covaxin (Doses Administered)"].sum()

5. Display total Covaxin doses administered for karnataka

260352181.0

In [10]:
print('6. Display total number doses for males and females administered for karnakata')
df.loc[df.State=="Karnataka","Male (Doses Administered)"].sum()
df.loc[df.State=="Karnataka","Female (Doses Administered)"].sum()

6. Display total number doses for males and females administered for karnakata

1059022410.0

In [12]:
print('7. Display total number of males and females administered dosage group by state')
df.groupby("State")["Male (Doses Administered)","Female (Doses Administered)"].agg(sum)

7. Display total number of males and females administered dosage group by state

C:\Users\Raghu Prasad\AppData\Local\Temp\ipykernel_11220\4212901599.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby("State")["Male (Doses Administered)","Female (Doses Administered)"].agg(sum)

,Male (Doses Administered),Female (Doses Administered)
State,,
Andaman and Nicobar Islands,1.045375e+07,8.964974e+06
Andhra Pradesh,6.776694e+08,7.550539e+08
Arunachal Pradesh,3.061580e+07,2.463594e+07
Assam,3.557939e+08,3.035113e+08
Bihar,8.693946e+08,7.472145e+08
Chandigarh,2.920781e+07,2.216730e+07
Chhattisgarh,4.381651e+08,4.507674e+08
Dadra and Nagar Haveli and Daman and Diu,2.378859e+07,1.263831e+07
Delhi,4.239074e+08,3.051522e+08
Goa,4.484737e+07,4.060736e+07
Gujarat,1.326683e+09,1.127534e+09
Haryana,4.635441e+08,3.859696e+08
Himachal Pradesh,1.783223e+08,1.830803e+08
India,9.937298e+09,8.660417e+09
Jammu and Kashmir,2.712608e+08,1.857529e+08
Jharkhand,3.627754e+08,3.094526e+08
Karnataka,1.061167e+09,1.059022e+09
Kerala,6.668392e+08,7.480674e+08
Ladakh,1.142961e+07,9.239169e+06
Lakshadweep,2.762047e+06,2.179428e+06
Madhya Pradesh,1.088844e+09,8.958841e+08
Maharashtra,1.728077e+09,1.470241e+09
Manipur,4.128041e+07,3.228720e+07
Meghalaya,3.624802e+07,3.275265e+07
Mizoram,2.739356e+07,2.650217e+07
Nagaland,2.776194e+07,1.978228e+07
Odisha,6.252842e+08,5.523907e+08
Puducherry,2.348317e+07,2.321824e+07
Punjab,3.706496e+08,2.859032e+08
Rajasthan,1.297273e+09,1.171015e+09
Sikkim,2.308142e+07,1.954897e+07
Tamil Nadu,7.595978e+08,6.883262e+08
Telangana,5.185786e+08,4.795398e+08
Tripura,1.160976e+08,1.088415e+08
Uttar Pradesh,1.757450e+09,1.329731e+09
Uttarakhand,2.151377e+08,2.020295e+08
West Bengal,1.167820e+09,9.601327e+08